### ISSUE TITLE
Argument Exception: Destination array is not long enough

### ISSUE THREAD

**Issue by cteodor** [EricZimmerman/MFTECmd#1]
Tried to run one of the examples:
Command line: -f mft --de 5-5
Error:
Unhandled Exception: System.ArgumentException: Destination array is not long enough to copy all the items in the collection. Check array index and length.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.BitConverter.ToInt16(Byte[] value, Int32 startIndex)
   at MFTECmd.Program.GetFileType(String file)
   at MFTECmd.Program.Main(String[] args)

MFTECmd version 0.3.6.1
Build from https://f001.backblazeb2.com/file/EricZimmermanTools/MFTECmd.zip

**Comment by EricZimmerman** [comment]
can i get the MFT in question? if not, can you use the --vl switch to get the offset, then use -dd and --do to send me just the offending record?

--vl will tell you if its free or not and i expect this is the issue

then again, its not happy about getting the file type.

how big is the file, and what do the first, say 50 bytes look like?

**Comment by EricZimmerman** [comment]
Second call for what i need to fix this issue. please let me know @cteodor

**Comment by EricZimmerman** [comment]
closing due to no activity from OP
